on:
  schedule:
  - cron: '*/30 * * * *'
jobs:
  zulip_archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Archive
      id: archive
      uses: zulip/zulip-archive@master
      with:
        zulip_organization_url: ${{ secrets.zulip_organization_url }}
        zulip_bot_email: ${{ secrets.zulip_bot_email }}
        zulip_bot_key: ${{ secrets.zulip_bot_key }}
        github_personal_access_token: ${{ secrets.gh_personal_access_token }}
        #delete_history: true
